//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeData_CRUD_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employeeid { get; set; }
        public string EmployeeNamee { get; set; }
        public string EmployeeGender { get; set; }
        public string EmployeeDesignation { get; set; }
        public string EmployeeAddress { get; set; }
        public Nullable<double> EmployeeContactNo { get; set; }
    }
}
